export const RECIPE = {
    title: 'Haleem',
    imgSrc: require('../assets/Haleem.jpg'),
    fontSrc: require('../assets/AnticDidone-Regular.ttf'),
    description:
      'Haleem is a type of stew that is widely consumed in South Asia, the Middle East and Central Asia. Although the dish varies from region to region, it optionally includes wheat or barley, meat and lentils. It is made by blending or mashing the meat in the curry and serving hot with flat breads or a variety of garnishes.',
    ingredients: [
      '1 tsp Cardamom',
      '1 tsp Coriander',
      '1 tsp Cumin',
      '1 tsp White Pepper',
      '6 Cloves',
      '2 Dry Chilies',
      '1 tsp Mustard Seeds',
      '2 Nutmeg Skins (Mace/Joitri)',
      '⅛ tsp Nutmeg',
      '1 tsp Fenugreek',
      '2 Sticks of Cinnamon',
      '1 Bay leaf',
      '¼ cup Whole Wheat Grain',
      '¼ cup Split Chickpeas',
      '¼ cup Mashkalai Dal/Black Lentils',
      '¼ cup Red Lentils',
      '¼ cup Moong Dal',
      '1 Onion',
      '1 kg Mutton',
      '1 tbsp Garlic Paste',
      '1 tbsp Ginger Paste',
      '½ tsp Turmeric',
      '1 tsp Red Chilli',
      '5 Green Chili',
      '1 tsp Roasted Cumin Powder',
      '1 tbsp Ghee',
      'Cilantro',
      'Thinly Sliced Ginger',
      'Chopped Green Chilli',
      'Fried Onion (Beresta)',
      'Lemon Wedges',
      'Chopped Hard Boiled Eggs',
    ],
    instructions: [
      'Soak whole wheat grain, split chickpeas, black lentils, red lentils and moong dal for 1 hr minimum.',
      'Toss whole spices in a dry skillet, stirring and tossing frequently over medium heat, until fragrant.',
      'Remove toasted spices from heat and blend',
      'Add salt to blended spices and store in an air tight container and stir before using.',
      'To a pot add onion, ginger, garlic, red chili, turmeric, roasted cumin powder, mustard seeds and saute for 10 min over high heat.',
      'Add mutton and saute for another 10 min.',
      'Add spice mix and salt to taste. ',
      'Pour 3-4 cups hot water and cook for 20 min over medium heat (cover with a lid and stir occasionally.)',
      'Add the soaked lentil mix, 2 cups of water, green chili and cook for 15 min.',
      'Set out the garnishes in bowls around the haleem.',
      'Serve the haleem hot in bowls and allow guests to add garnishes before eating',
    ],
  }